### ISSUE TITLE
Non-blocking read for keyboard events

### ISSUE THREAD

**Issue by ghost** [m2i/AccessControlBox#3]
The `read()` call will block until data is ready, we need to use `select()` to go to non-blocking so that we can disable access if the card is removed.

**Comment by Talonj123** [comment]
We can also set the file descriptor into non-blocking mode?

**Comment by ghost** [comment]
Done. There are parameters for the timeout and a retry count. The current total card timeout (application level) is ~5 seconds, with 10 retries in that time.
